name: Book and Sign Seats

on:
  # 定时触发器，使用 Cron 表达式
  schedule:
    # 每天的 6:15 运行预约脚本
    - cron: '15 6 * * *'
    # 每天的 9:21、9:31、9:35、9:55、14:31、14:55、18:31运行签到脚本
    - cron: '21,31,35,55 9,14,18 * * *'

  # 手动触发工作流
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码到 runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: 运行预约脚本
      - name: Run Reserve Script
        run: |
          python reserve.py

  sign:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码到 runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: 运行签到脚本
      - name: Run Sign Script
        run: |
          python sign.py