name: Book and Sign Seats

on:
  schedule:
    - cron: '15 22 * * *'
    - cron: '21,31,42,55 1,6,10,11 * * *'
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Reserve Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_DEVNAME: ${{ secrets.USER_DEVNAME }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python reserve.py

  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Sign Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_DEVNAME: ${{ secrets.USER_DEVNAME }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python sign.py
