name: Book and Sign Seats

on:
  schedule:
    - cron: '55 21 * * *'  # 北京时间 5:55
    - cron: '2 22 * * *'   # 北京时间 6:00
    - cron: '7 22 * * *'   # 北京时间 6:05
    - cron: '12 22 * * *'  # 北京时间 6:10
    - cron: '17 22 * * *'  # 北京时间 6:15
    - cron: '22 22 * * *'  # 北京时间 6:20
    - cron: '30,45,55 0 * * *'
    - cron: '55 5 * * *'
    - cron: '7,21,32,40 6,10 * * *'
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Reserve Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python reserve.py

  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Sign Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python sign.py
