name: Book and Sign Seats

on:
  schedule:
    - cron: '13 22 * * *'   # 北京时间 6:00
    - cron: '18 22 * * *'  # 北京时间 6:05
    - cron: '0,30 0 * * *'  # 9:30 时段签到
    - cron: '55 5,9 * * *'
    - cron: '0,15,25,35 6,10 * * *'
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Reserve Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python reserve.py

  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Sign Script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_SNO: ${{ secrets.USER_SNO }}
          USER_PWD: ${{ secrets.USER_PWD }}
          USER_PUSHPLUS: ${{ secrets.USER_PUSHPLUS }}
        run: |
          python sign.py
